### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by novauto-nju** [Andy97/DeepMLS#1]
When using Python build.py -- cuda-/usr/local/cuda-10.0, I encountered the following problem:tensorflow.python.framework.errors_impl.NotFoundError: libcudart.so.10.0: cannot open shared object file: No such file or directory

**Comment by Andy97** [comment]
Hi, it seems like the cuda runtime library is not found. Please check if cuda 10.0 is installed and if following environment variables are set properly: 
```
export PATH="/usr/local/cuda-10.0/bin:$PATH"
export CUDA_HOME="/usr/local/cuda-10.0"
export LD_LIBRARY_PATH="/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="/usr/local/cuda-10.0/extras/CUPTI/lib64:$LD_LIBRARY_PATH"
```

**Comment by novauto-nju** [comment]
OK！I have set the above four environment variables. I use the virtual environment of conda, in addition to installing environment.yml, my cmake = = 3.19.6, cudatoolkit = = 10.0.130.But using Python build.py -- cuda-/usr/local/cuda-10.0, I encountered the following problem:`2021-05-12 23:09:54.646927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-12 23:09:54.646975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
ERROR:tensorflow:No OpKernel was registered to support Op 'OctreeAlign' used by node OctreeAlign (defined at /home/zenghui/.conda/envs/deep_mls/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [depth=5]
Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
  device='GPU'

         [[OctreeAlign]]
`

**Comment by novauto-nju** [comment]
OK！I have set the above four environment variables. I use the virtual environment of conda, in addition to installing environment.yml, my cmake = = 3.19.6, cudatoolkit = = 10.0.130.But using Python build.py -- cuda-/usr/local/cuda-10.0, I encountered the following problem:

2021-05-12 23:09:54.646927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:

2021-05-12 23:09:54.646975: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]

ERROR:tensorflow:No OpKernel was registered to support Op 'OctreeAlign' used by node OctreeAlign (defined at /home/zenghui/.conda/envs/deep_mls/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) with these attrs: [depth=5]

Registered devices: [CPU, XLA_CPU, XLA_GPU]
Registered kernels:
device='GPU'

**Comment by novauto-nju** [comment]
OK!  I have solved this problem.Thanks!

2021-05-13 00:38:45.722670: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 21483 MB memory) -> physical GPU (device: 0, name: PH402 SKU 200, pci bus id: 0000:06:00.0, compute capability: 6.0)
[       OK ] test_points_property.PointsPropertyTest.test_points_property
[ RUN      ] test_points_property.PointsPropertyTest.test_session
[  SKIPPED ] test_points_property.PointsPropertyTest.test_session
----------------------------------------------------------------------
Ran 30 tests in 58.314s

OK (skipped=11)

**Comment by novauto-nju** [comment]
you need install tensorflow-gpu=1.15.0 again.Also install numpy =1.17.2
